### ISSUE TITLE
[aur] Build Issue with fishui-git

### ISSUE THREAD

**Issue by themagicalmammal** [eyenpi/cutefish-git#1]
-- Found SoundThemeFreeDesktop: /usr/share/sounds/freedesktop/index.theme  
-- Checking for module 'libpulse'
--   Found libpulse, version 15.0
-- Checking for module 'libpulse-mainloop-glib'
--   Found libpulse-mainloop-glib, version 15.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/themage/.cache/yay/libcutefish-git/src/libcutefish
[67/104] Building CXX object screen/CMakeFiles/cutefishscreen_qmlplugins.dir/outputmodel.cpp.o
FAILED: screen/CMakeFiles/cutefishscreen_qmlplugins.dir/outputmodel.cpp.o 
/usr/bin/c++ -DKCOREADDONS_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICK_LIB -DQT_SENSORS_LIB -DQT_TESTCASE_BUILDDIR=\"/home/themage/.cache/yay/libcutefish-git/src/libcutefish\" -DQT_TESTLIB_LIB -Dcutefishscreen_qmlplugins_EXPORTS -I/home/themage/.cache/yay/libcutefish-git/src/libcutefish/screen -I/home/themage/.cache/yay/libcutefish-git/src/libcutefish/screen/cutefishscreen_qmlplugins_autogen/include -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtQuick -isystem /usr/include/qt/QtQmlModels -isystem /usr/include/qt/QtQml -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtDBus -isystem /usr/include/qt/QtSensors -isystem /usr/include/qt/QtTest -isystem /usr/include/KF5/KScreen -isystem /usr/include/KF5/KIOCore -isystem /usr/include/KF5/KIO -isystem /usr/include/KF5 -isystem /usr/include/KF5/KCoreAddons -isystem /usr/include/KF5/KService -isystem /usr/include/KF5/KConfig -isystem /usr/include/KF5/KConfigCore -isystem /usr/include/qt/QtConcurrent -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -fPIC -fPIC -std=gnu++14 -MD -MT screen/CMakeFiles/cutefishscreen_qmlplugins.dir/outputmodel.cpp.o -MF screen/CMakeFiles/cutefishscreen_qmlplugins.dir/outputmodel.cpp.o.d -o screen/CMakeFiles/cutefishscreen_qmlplugins.dir/outputmodel.cpp.o -c /home/themage/.cache/yay/libcutefish-git/src/libcutefish/screen/outputmodel.cpp
/home/themage/.cache/yay/libcutefish-git/src/libcutefish/screen/outputmodel.cpp: In member function ‘bool OutputModel::setReplicationSourceIndex(int, int)’:
/home/themage/.cache/yay/libcutefish-git/src/libcutefish/screen/outputmodel.cpp:606:21: error: ‘class KScreen::Output’ has no member named ‘setLogicalSize’
  606 |         output.ptr->setLogicalSize(QSizeF());
      |                     ^~~~~~~~~~~~~~
/home/themage/.cache/yay/libcutefish-git/src/libcutefish/screen/outputmodel.cpp:617:21: error: ‘class KScreen::Output’ has no member named ‘setLogicalSize’
  617 |         output.ptr->setLogicalSize(source->logicalSize());
      |                     ^~~~~~~~~~~~~~
/home/themage/.cache/yay/libcutefish-git/src/libcutefish/screen/outputmodel.cpp:617:44: error: ‘class KScreen::Output’ has no member named ‘logicalSize’
  617 |         output.ptr->setLogicalSize(source->logicalSize());
      |                                            ^~~~~~~~~~~
[69/104] Building CXX object screen/CMakeFiles/cutefishscreen_qmlplugins.dir/screen.cpp.o
/home/themage/.cache/yay/libcutefish-git/src/libcutefish/screen/screen.cpp: In constructor ‘Screen::Screen(QObject*)’:
/home/themage/.cache/yay/libcutefish-git/src/libcutefish/screen/screen.cpp:12:33: warning: ‘int qmlRegisterType() [with T = OutputModel]’ is deprecated: Use qmlRegisterAnonymousType instead [-Wdeprecated-declarations]
   12 |     qmlRegisterType<OutputModel>();
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/qt/QtQml/qqmlengine.h:47,
                 from /usr/include/qt/QtQml/QQmlEngine:1,
                 from /home/themage/.cache/yay/libcutefish-git/src/libcutefish/screen/screen.cpp:7:
/usr/include/qt/QtQml/qqml.h:183:74: note: declared here
  183 | QT_DEPRECATED_VERSION_X_5_14("Use qmlRegisterAnonymousType instead") int qmlRegisterType()
      |                                                                          ^~~~~~~~~~~~~~~
[72/104] Automatic MOC and UIC for target cutefishaudio_qmlplugins
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by eyenpi** [comment]
It's upstream issue. Check out this issue:
https://github.com/cutefishos/libcutefish/issues/7
